name: Deploy the new code

on:
  workflow_dispatch:
    branch:
      - main:

jobs:
  built-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
  deploy:
    steps:
      - name: Deploy the code
        run: echo "Deploy the code"
